// YOLO Object Detection with WASI-NN Component
// Uses wit-bindgen generated bindings from Bazel

// Use the bindings generated by Bazel (yolo_inference_bindings crate)
extern crate yolo_inference_bindings as bindings;

// Re-export bindings for internal use
use bindings::exports::wasi::cli::run::Guest;

// YOLO detection module
#[path = "yolo_inference.rs"]
mod yolo_inference;

// Component implementation struct
struct YoloComponent;

// Implement the wasi:cli/run interface
impl Guest for YoloComponent {
    fn run() -> Result<(), ()> {
        yolo_inference::run_yolo();
        Ok(())
    }
}

// Export the component - this wires up the WASM exports
bindings::export!(YoloComponent with_types_in bindings);
