// Async text-processor P3 component.
//
// Exports two async interfaces:
//   analyzer  — statistics, word frequencies, pattern search
//   transformer — case conversion, reversal, Caesar cipher, substitution
//
// The #[cfg] gates keep the source compilable on both wasm32 (async trait
// generated by wit-bindgen --async) and the host (sync trait, useful for
// cargo check / IDE support).

use std::collections::{HashMap, HashSet};

use text_processor_bindings::exports::text::processor::analyzer::{
    Guest as AnalyzerGuest, TextStats, WordEntry,
};
use text_processor_bindings::exports::text::processor::transformer::{
    Guest as TransformerGuest, TransformMode,
};

struct Component;

// ---------------------------------------------------------------------------
// Core logic (sync, shared by both cfg paths)
// ---------------------------------------------------------------------------

impl Component {
    fn do_analyze(text: &str) -> TextStats {
        let words: Vec<&str> = text.split_whitespace().collect();
        let char_count = text.chars().count() as u32;
        let word_count = words.len() as u32;
        let line_count = if text.is_empty() {
            0
        } else {
            text.lines().count() as u32
        };

        let unique: HashSet<String> = words.iter().map(|w| w.to_lowercase()).collect();
        let unique_word_count = unique.len() as u32;

        let avg_word_length = if words.is_empty() {
            0.0
        } else {
            words.iter().map(|w| w.len() as f32).sum::<f32>() / words.len() as f32
        };

        TextStats {
            char_count,
            word_count,
            line_count,
            unique_word_count,
            avg_word_length,
        }
    }

    fn do_word_frequencies(text: &str) -> Vec<WordEntry> {
        let mut freq: HashMap<String, u32> = HashMap::new();
        for word in text.split_whitespace() {
            *freq.entry(word.to_lowercase()).or_insert(0) += 1;
        }
        let mut entries: Vec<WordEntry> = freq
            .into_iter()
            .map(|(word, count)| WordEntry { word, count })
            .collect();
        // Descending by count, then alphabetical for stability.
        entries.sort_by(|a, b| b.count.cmp(&a.count).then(a.word.cmp(&b.word)));
        entries
    }

    fn do_search_positions(text: &str, pattern: &str) -> Vec<u32> {
        if pattern.is_empty() {
            return Vec::new();
        }
        text.match_indices(pattern).map(|(i, _)| i as u32).collect()
    }

    fn do_transform(text: &str, mode: TransformMode) -> String {
        match mode {
            TransformMode::Uppercase => text.to_uppercase(),
            TransformMode::Lowercase => text.to_lowercase(),
            TransformMode::Reverse => text.chars().rev().collect(),
            TransformMode::TitleCase => text
                .split_whitespace()
                .map(|w| {
                    let mut chars = w.chars();
                    match chars.next() {
                        None => String::new(),
                        Some(c) => {
                            c.to_uppercase().to_string() + &chars.as_str().to_lowercase()
                        }
                    }
                })
                .collect::<Vec<_>>()
                .join(" "),
        }
    }

    fn do_caesar_cipher(text: &str, shift: i32) -> String {
        let shift = ((shift % 26) + 26) % 26;
        text.chars()
            .map(|c| {
                if c.is_ascii_lowercase() {
                    (b'a' + (((c as u8 - b'a') as i32 + shift) % 26) as u8) as char
                } else if c.is_ascii_uppercase() {
                    (b'A' + (((c as u8 - b'A') as i32 + shift) % 26) as u8) as char
                } else {
                    c
                }
            })
            .collect()
    }

    fn do_replace_all(text: &str, pattern: &str, replacement: &str) -> String {
        text.replace(pattern, replacement)
    }
}

// ---------------------------------------------------------------------------
// Analyzer (async on wasm32, sync on host)
// ---------------------------------------------------------------------------

impl AnalyzerGuest for Component {
    #[cfg(target_arch = "wasm32")]
    async fn analyze(text: String) -> TextStats {
        Self::do_analyze(&text)
    }
    #[cfg(not(target_arch = "wasm32"))]
    fn analyze(text: String) -> TextStats {
        Self::do_analyze(&text)
    }

    #[cfg(target_arch = "wasm32")]
    async fn word_frequencies(text: String) -> Vec<WordEntry> {
        Self::do_word_frequencies(&text)
    }
    #[cfg(not(target_arch = "wasm32"))]
    fn word_frequencies(text: String) -> Vec<WordEntry> {
        Self::do_word_frequencies(&text)
    }

    #[cfg(target_arch = "wasm32")]
    async fn search_positions(text: String, pattern: String) -> Vec<u32> {
        Self::do_search_positions(&text, &pattern)
    }
    #[cfg(not(target_arch = "wasm32"))]
    fn search_positions(text: String, pattern: String) -> Vec<u32> {
        Self::do_search_positions(&text, &pattern)
    }
}

// ---------------------------------------------------------------------------
// Transformer (async on wasm32, sync on host)
// ---------------------------------------------------------------------------

impl TransformerGuest for Component {
    #[cfg(target_arch = "wasm32")]
    async fn transform(text: String, mode: TransformMode) -> String {
        Self::do_transform(&text, mode)
    }
    #[cfg(not(target_arch = "wasm32"))]
    fn transform(text: String, mode: TransformMode) -> String {
        Self::do_transform(&text, mode)
    }

    #[cfg(target_arch = "wasm32")]
    async fn caesar_cipher(text: String, shift: i32) -> String {
        Self::do_caesar_cipher(&text, shift)
    }
    #[cfg(not(target_arch = "wasm32"))]
    fn caesar_cipher(text: String, shift: i32) -> String {
        Self::do_caesar_cipher(&text, shift)
    }

    #[cfg(target_arch = "wasm32")]
    async fn replace_all(text: String, pattern: String, replacement: String) -> String {
        Self::do_replace_all(&text, &pattern, &replacement)
    }
    #[cfg(not(target_arch = "wasm32"))]
    fn replace_all(text: String, pattern: String, replacement: String) -> String {
        Self::do_replace_all(&text, &pattern, &replacement)
    }
}

text_processor_bindings::export!(Component with_types_in text_processor_bindings);
